controllernav: { 
  Gp_trajectory: 0.2,#0.2
  Gp_map_correction: 0.0,
  
  collision_avoidance_treshold: 0.15, #meters
  
  control_freq: 50,
  control_time: 0.02,
  satMin: 40.0,
  satMax: 150.0,
  linearSpeed: 0.2
}
